### ISSUE TITLE
Implement Pet Service

### ISSUE THREAD

**Issue by JoshuaJLi** [bryanjhdang/tempify#18]
The PetService controls user coins and information retaining to a user's pet. It has 3 endpoints that need their service implementations to work. Endpoint in/out requirements can be gleamed from the controller class.

- `GET /coins`
Returns the number of coins a user has

- `POST /coins`
(low priority) Adds the specified number of coins to the user's total, returns the new total

- `GET /`
returns name and image URL about a user's pet

**Comment by bryanjhdang** [comment]
The branch `18-implement-pet-service` is still open with stubs for all of the implementations. Currently, Firestore is not set up so it will remain incomplete but once it is we can revisit this branch.

**Comment by bryanjhdang** [comment]
I think this is done?
